### ISSUE TITLE
"Submit" translation section via GitLocalize doesn't work

### ISSUE THREAD

**Issue by troyane** [zbroyar/mass_killings#45] opened 2022-04-16 17:51 UTC
Click on the "Submit" button makes it disabled and remains the same:

![image](https://user-images.githubusercontent.com/477468/163685931-34ce4908-01fd-43aa-a6d4-a009f7403e1e.png)

No changes to text saved.

@ilyaspiridonov, is it related to the known issue?

**Comment by paul1974nsac** [comment] 2022-05-02 12:06
Duplicate of #45

**Comment by igorbrigadir** [comment] 2022-10-05 16:00
This seems to work for me now, i can submit successfully.

**Closed** 2022-10-13 21:30 UTC
